#!/usr/bin/env bash
CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

tmux run-shell -b "$CURRENT_DIR/scripts/features/sidebar/configure-pane-border-format.sh"
tmux bind-key t run-shell -b "$CURRENT_DIR/scripts/features/sidebar/toggle-sidebar.sh"
tmux bind-key T run-shell -b "$CURRENT_DIR/scripts/features/sidebar/focus-sidebar.sh"
tmux set-hook -g "client-active[198]" "run-shell -b '$CURRENT_DIR/scripts/features/sidebar/ensure-sidebar-pane.sh'"
tmux set-hook -g "client-attached[199]" "run-shell -b '$CURRENT_DIR/scripts/features/sidebar/ensure-sidebar-pane.sh'"
tmux set-hook -g "client-session-changed[200]" "run-shell -b '$CURRENT_DIR/scripts/features/sidebar/on-pane-focus.sh #{pane_id} #{window_id}'"
tmux set-hook -g "client-focus-in[202]" "run-shell -b '$CURRENT_DIR/scripts/features/sidebar/on-pane-focus.sh #{pane_id} #{window_id}'"
tmux set-hook -g "after-select-window[203]" "run-shell -b '$CURRENT_DIR/scripts/features/sidebar/on-pane-focus.sh #{pane_id} #{window_id}'"
tmux set-hook -g "after-select-pane[204]" "run-shell -b '$CURRENT_DIR/scripts/features/sidebar/on-pane-focus.sh #{pane_id} #{window_id}'"
tmux set-hook -g "session-window-changed[205]" "run-shell -b '$CURRENT_DIR/scripts/features/sidebar/on-pane-focus.sh #{pane_id} #{window_id}'"
tmux set-hook -g "after-split-window[206]" "run-shell -b '$CURRENT_DIR/scripts/features/sidebar/notify-sidebar.sh'"
tmux set-hook -g "after-new-window[207]" "run-shell -b '$CURRENT_DIR/scripts/features/sidebar/ensure-sidebar-pane.sh'"
tmux set-hook -g "after-kill-pane[208]" "run-shell -b '$CURRENT_DIR/scripts/features/sidebar/handle-pane-exited.sh #{hook_pane} #{hook_window}'"
tmux set-hook -g "after-resize-pane[209]" "run-shell -b '$CURRENT_DIR/scripts/features/sidebar/notify-sidebar.sh'"
tmux set-hook -g "after-rename-window[210]" "run-shell -b '$CURRENT_DIR/scripts/features/sidebar/notify-sidebar.sh'"
tmux run-shell -b "$CURRENT_DIR/scripts/features/sidebar/apply-key-overrides.sh"
tmux run-shell -b "bash $CURRENT_DIR/scripts/features/context-menu/bind-context-menu.sh"  # right-click context menu
